### ISSUE TITLE
Issues building Perun

### ISSUE THREAD

**Issue by brucellino** [CESNET/perun#1405]
Helo Perun devs.

I'm deploying perun for AfricaGrid with the [ansible playbook](https://github.com/CESNET/ansible-perun) developed by @zwejra. The playbook itself looks good so far, but I'm getting maven errors. 

They seem to be mostly checkstyle errors (tabs vs spaces) - but this is failing the task.

If these errors are "real", I'll pass you a full log of the output, but I'm assuming they're just very severe warnings for now. Can you let me know what options to pass to maven to avoid these errors ?

**Comment by zlamalp** [comment]
Hi Bruce,

spaces/tabs should be only warning, that can be ignored. We build perun with maven 3.0.5 in top project folder like this.

perun-rpc (war):
```
mvn -pl perun-rpc -am clean install -Dproduction -DskipTests
```
perun-engine (jar):
```
mvn -pl perun-engine -am clean package dependency:copy-dependencies -Dproduction -DskipTests
```
I'm not sure, why it should fail build, maybe some settings became default in newer version. Try to look for something like "do not fail on warning". You can also check "checkstyle" plugin settings in main peruns pom.xml.

**Comment by brucellino** [comment]
hi @zlamalp, thanks for the explanation. Indeed spaces/tabs _is_ the only warning.

I should point out that the _build_ is not failing (the artefacts are all built correctly), it is the Ansible _task_ that is failing. This is only relatively important, since we can easily fail the build in some other way. 

However, I would like to disable style checks completely. How does one do that with maven ?

**Comment by zlamalp** [comment]
Hi @brucellino, by its docs you can disable checkstyle plugin on commandline by passing:
```
-Dcheckstyle.skip=true
```

**Comment by brucellino** [comment]
Děkuji mnohokrát!
