### ISSUE TITLE
getAllowedUsers for resources returns allowed when user is EXPIRED

### ISSUE THREAD

**Issue by dBucik** [CESNET/perun#1979]
*class: cz.metacentrum.perun.core.impl.ResourcesManagerImpl
*method: public List<User> getAllowedUsers(PerunSession sess, Resource resource)
*environment: Resource with assigned "members" group. User is EXPIRED in the VO for which the resource is created.
*problem: Method checks only if the member is INVALID / DISABLED. I would expect only VALID members are allowed on the resource.
Is this behavior intended?

**Comment by licehammer** [comment]
Yes, it is intended.

**Comment by dBucik** [comment]
Thank you for the explanation. We were trying to use the function in a bad manner then.
